sudo: required

dist: trusty

#osx_image: xcode7.3

os:
  - linux
#  - osx

language: node_js

node_js:
  - node

branches:
  only: master

before_install:
#  - curl -XPURGE "https://camo.githubusercontent.com/9ef7a5cd3411885c59a9ece91514b084371f7049/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f646f776e6c6f6164732f63747562696f2f4b727970746f2d74726164696e672d626f742f746f74616c2e7376673f6d61784167653d32353932303030266c6162656c3d646f776e6c6f6164732532306c6173742532303231253230636f6d6d697473";
  - test $TRAVIS_OS_NAME == "osx" && brew install --with-default-names gnu-sed || :;
  - test $TRAVIS_OS_NAME == "linux" && make travis || :;

install:
  - yes 1 | make install

script: make test-cov

after_success: make send-cov

notifications:
  email:
    on_success: never
