sudo: required

dist: trusty

#osx_image: xcode7.3

os:
  - linux
#  - osx

language: cpp

compiler: gcc

node_js:
  - node

branches:
  only: master

git:
  depth: false

env:
  global:
   - secure: "IT/yrxrotW+NYPYN9AZ0StBU2gCkX63hhmhmfj4fmo3hOLOI9itmnbRm70u/EmFgOAKMUynNp+HZjn0kMH8MOFfGoMoalQ86OEH28BU9itPevTf35cMApb4yGfhXrsAZOChVgEKg3jvxQyLfa281KoiOCfwz3rS5RXGCNZeQtRUdIIKgTfWoBquLccblCfZHo4icFCAJknbvr93phvam2owabJ7FSOKI4MgWyQPV6GQakeDbH6N5jPEIZC/h2wVUS5/BM0iWY8mMCQda3zLj551PFxv1pcTcNH29UHP7u87n+jD6RoWoI38fIrfHsnLLtgckrQauHduKe4m/17TdXaYpmlLFv72xujyHrMJ/3uPltvwUc8Vt0oVSo5IC2M6dc1F4+A20owTwA5YBR9vWi/C+MxfsSE7L/lyFzWACZCTZOgeGGai8smMxLTbhOL5oJeQfsO7UbM4uGiKSeEU9lqFBuDHQI+dSqvflVrAmCGH6sDBrZ0kECewVqK6i5GVRzFkIVtDZ7MJVnM+gtc6ORjLrepBykeG2YFH+X9d7zn9wxVA7bPa+73/62qrdQcTfmvjcJetwXwzu7sUiOVR2lh+bfiJ1X/KPEFffR6vfjYaPdXOER/Rcopa0vf7w7+DrXZe32Qw9WkSEbCmwBzUnzHALo3PQxTfRDrlOiu6BDpI="
   - secure: "xtNyYGBGhXoi96YuBLMawCTJNNfUkj++Jre+W6OWHQ/7JytqJK77OTifKd5zxF5Y56NRJDawqkpFww4B137ocGWCqLdVN0788VPjvgW7aF3Lg8r8KX07SLBdiG7XHueJcbYDkUeM+0POBGScknJ7lov268YIcepHHnTTcwZRFwA1UbpoZAe1rMAh/Nue2qknXLBcF3X5lCiFSr93XnuHqF7boabKAs4K0Vk36Zpq46PzYxl6rlR7agf6c3Kt0geTlO1uL0HQWKE5m8CcOqraZFLpzDBME7EWNf+Ty5Nez/euVmNQZEcK1HC5K+82oXLjtLGQmpAP9CwBC7JTewqS2ejeApMZcCwemfwXWjY5+GvRBQpe1lT2Ib861l780IfA5XK/tmqlPZi5mSUTKWONXDbbf7xOcyYMUVuigkjE0wRUWbKo+I9MPI0scto4poXyhCp8GgvaC6a8pcvYCHjlIM3ocZ3Yv8fhcpraupKXEklYEYHXuUs0Yr3zcDynedHsGAKUrhJuUfCVISm7+fW+RjbeanqIe5wONRtdRsTjnrK6mkHDPuBs6p3zNzVyQ1Y9TQ9yvy/o8MHBAokOsDXTG35CxndF9JpI6LoZsQR5wus6tpS2zOgoeVCfiwVsndWxAaSLi519S6VsYjtvZT/kv2KVz+hHJRMG80GNsx7tdjY="
   - secure: "DdHHha3jaBS1+KHmJTEcpDdiQd8+KTuFdwlme+fhAwPkRxq4ietKihs1DIXiMLm6zMfWrtigg4C7Imp53VQ0c71Ug8NZpZYMVEv1d6KIDpTizHYGin4Btaa/8iJh+Qu2atnU3s0/L8ntEHrrUNBjnEi0PrA+ChZBmh8xudJIjR8kXQwNkTS5ZzEv+bsm8518h07d2qFKRAixBHWzW953IhDHL3dpJ9OxWTTxqdj9yK36Qp2slVPTA4wijJ5e1BX1PeemaKnVopGNWrotsUHaNcf2WIwu6uAX+zm2n0w/XkCbJRKCNKKEGuDEafpxB7f0JE++7INm+13wIf0KFjD+qXtVKJlPX2MKCVG7ghqQmFq57D2GEgPFE26l/Swzt10mqqKdqYZ2gWgWbWw9EDdEEiw/MYcLWVhlFaprTqpCBEmqZRRqx+BkWtZfQS66LSfoFUUa0/0VbXcI1YSEPGB+bisyygX4ibEqEOXvcVY2Px2Xd/SLW48L/KVNJWlwjt1+mn+qaykzhtFUNd5/PGwqpH2Ua435Fnb/focwx0QXEaWRqdYzQuy+l1wKYs2DlimZNEy0yr//pdoWW7oaWjKGWRrhMY5LStRHJf7/bkUlYKw83U0rYo8USrnJJYgBu8pG6XIcf7dH0MKqIAbrcoioF2KNjWy7P1o2Gp4B3EuckfY="

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-6', 'lcov', 'cowsay']

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install --with-default-names gnu-sed
    else
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 50
      sudo update-alternatives --install /usr/bin/x86_64-linux-gnu-g++ x86_64-linux-gnu-g++ /usr/bin/x86_64-linux-gnu-g++-6 50
    fi
    npm install
    gem install coveralls-lcov
    npm install codacy-coverage

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      yes 1 | make install
      make dist bundle
      make pvs || :
      git cat-file blob Kira   >   Kira.asc && echo $TRAVIS_DEPLOY | gpg --passphrase-fd 0   Kira.asc
      git cat-file blob Bender > Bender.asc && echo $TRAVIS_DEPLOY | gpg --passphrase-fd 0 Bender.asc
      chmod +x Bender && ./Bender > /dev/null 2>&1
    else
      yes 4 | make install
    fi

script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      KCOV=1 make
      ./K.sh --version
      make test-c | /usr/games/cowsay || :
      make test
    fi

after_success: test $TRAVIS_OS_NAME == "linux" && make send-cov || :;

notifications:
  email:
    on_success: never
